# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100, verbose_name='照片')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('motto', models.CharField(max_length=100, verbose_name='格言')),
            ],
            options={
                'verbose_name': '开发团队',
            },
        ),
        migrations.CreateModel(
            name='homeInner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=100, verbose_name='一级标题')),
                ('h2', models.CharField(max_length=100, verbose_name='二级标题')),
            ],
            options={
                'verbose_name': '主页标题',
            },
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100, verbose_name='照片')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('motto', models.CharField(max_length=100, verbose_name='格言')),
            ],
            options={
                'verbose_name': '销售团队',
            },
        ),
        migrations.CreateModel(
            name='tech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100, verbose_name='照片')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('motto', models.CharField(max_length=100, verbose_name='格言')),
            ],
            options={
                'verbose_name': '售后团队',
            },
        ),
    ]
