# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200, verbose_name='图片')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('text', models.CharField(max_length=500, verbose_name='内容')),
            ],
            options={
                'verbose_name': '案例',
            },
        ),
        migrations.CreateModel(
            name='homeInner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=100, verbose_name='一级标题')),
                ('h2', models.CharField(max_length=100, verbose_name='二级标题')),
            ],
            options={
                'verbose_name': '主页标题',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro', models.CharField(max_length=50, verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品',
            },
        ),
    ]
