# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='职位')),
                ('welfare', models.CharField(max_length=100, verbose_name='福利')),
                ('salary', models.CharField(max_length=100, verbose_name='薪资')),
                ('requirements', models.CharField(max_length=100, verbose_name='要求')),
            ],
            options={
                'verbose_name': '招聘',
            },
        ),
        migrations.CreateModel(
            name='homeInner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=100, verbose_name='一级标题')),
                ('h2', models.CharField(max_length=100, verbose_name='二级标题')),
            ],
            options={
                'verbose_name': '主页标题',
            },
        ),
    ]
